fixing indent

diff --git a/ValidateCommitMessage.yml b/ValidateCommitMessage.yml
--- a/ValidateCommitMessage.yml
+++ b/ValidateCommitMessage.yml
@@ -17,18 +17,18 @@ jobs:
     vmImage: ubuntu-latest
   steps:
   - checkout: self
-- script: |
-    # Ensure we have full commit history in the CI environment
-    git fetch --all --unshallow
+  - script: |
+      # Ensure we have full commit history in the CI environment
+      git fetch --all --unshallow
 
-    # Find the last non-merge commit before the merge commit (PR source commit)
-    last_commit_message=$(git log -1 --pretty=%s $(git rev-list --no-merges -n 1 HEAD))
+      # Find the last non-merge commit before the merge commit (PR source commit)
+      last_commit_message=$(git log -1 --pretty=%s $(git rev-list --no-merges -n 1 HEAD))
 
-    if [[ $last_commit_message =~ version\ ?[0-9]+\.[0-9]+\.[0-9]+ ]]; then
-      echo "Commit message contains a valid version format: $last_commit_message"
-    else
-      echo "Error: The commit message does not contain a valid version format (versionX.X.X)."
-      echo "Last commit message: $last_commit_message"
-      exit 1
-    fi
-  displayName: "Check commit message format"
+      if [[ $last_commit_message =~ version\ ?[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+        echo "Commit message contains a valid version format: $last_commit_message"
+      else
+        echo "Error: The commit message does not contain a valid version format (versionX.X.X)."
+        echo "Last commit message: $last_commit_message"
+        exit 1
+      fi
+    displayName: "Check commit message format"
